name: Push to Replicate

on:
  # Workflow dispatch allows you to manually trigger the workflow from GitHub.com
  # Go to your repo, click "Actions", click "Push to Replicate", click "Run workflow"
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Enter the model name, like "ditto--ai/qwen3guard-gen-4b". If unset, this will default to the value of `image` in cog.yaml.'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  push_to_replicate:
    name: Push to Replicate

    # If your model is large, the default GitHub Actions runner may not
    # have enough disk space. If you need more space you can set up a
    # bigger runner on GitHub.
    runs-on: ubuntu-latest

    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false

      - name: Checkout
        uses: actions/checkout@v4

      # This action installs Docker buildx and Cog (and optionally CUDA)
      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}
          cog-version: "v0.17.2"

      # If you trigger the workflow manually, you can specify the model name.
      # If you leave it blank (or if the workflow is triggered by a push), the
      # model name will be derived from the `image` value in cog.yaml.
      - name: Push to Replicate
        env:
          MODEL_NAME: ${{ inputs.model_name }}
        run: |
          if [ -n "$MODEL_NAME" ]; then
            cog push "r8.im/$MODEL_NAME"
          else
            cog push
          fi
